### PR TITLE
Handle preshader instructions that use inregs as scratch registers

### PR DESCRIPTION
**Pull request by kg**

### CODE REVIEW

**Comment by kg** [comment]
FTR, while this gets rid of the runtime assert for me, my shaders seem to work and it makes logical sense, I'm not totally sure this is the right behavior - so I wouldn't treat this as correct unless I'm the only person who really uses preshaders enough to care about a minor bug that might have slipped in. I haven't been able to find any documentation for this stuff.

**Comment by flibitijibibo** [comment]
Ignoring style stuff this appears to `alloca` a temp register array only to not use it...?

Here's the hg diff after my review pass, does this look good to you?

```
diff -r 21422b28cfd4 mojoshader_effects.c
--- a/mojoshader_effects.c      Mon May 27 03:09:07 2019 -0400
+++ b/mojoshader_effects.c      Wed May 29 13:52:30 2019 -0400
@@ -17,7 +17,7 @@
 void MOJOSHADER_runPreshader(const MOJOSHADER_preshader *preshader,
                              float *outregs)
 {
-    const float *inregs = preshader->registers;
+    float *inregs = preshader->registers;
 
     // this is fairly straightforward, as there aren't any branching
     //  opcodes in the preshader instruction set (at the moment, at least).
@@ -188,11 +188,19 @@
                     operand->index + (elemsbytes / sizeof (double)));
             memcpy(temps + operand->index, dst, elemsbytes);
         } // if
+        else if (operand->type == MOJOSHADER_PRESHADEROPERAND_OUTPUT)
+        {
+            for (i = 0; i < elems; i++)
+                outregs[operand->index + i] = (float) dst[i];
+        } // else if
+        else if (operand->type == MOJOSHADER_PRESHADEROPERAND_INPUT)
+        {
+            for (i = 0; i < elems; i++)
+                inregs[operand->index + i] = (float) dst[i];
+        } // else if
         else
         {
-            assert(operand->type == MOJOSHADER_PRESHADEROPERAND_OUTPUT);
-            for (i = 0; i < elems; i++)
-                outregs[operand->index + i] = (float) dst[i];
+            assert(0 && "Unhandled preshader operand type!");
         } // else
     } // for
 } // MOJOSHADER_runPreshader
diff -r 21422b28cfd4 utils/testparse.c
--- a/utils/testparse.c Mon May 27 03:09:07 2019 -0400
+++ b/utils/testparse.c Wed May 29 13:52:30 2019 -0400
@@ -173,9 +173,12 @@
         case MOJOSHADER_PRESHADEROPERAND_TEMP:
         {
             int idx = operand->index % 4;
-            char regch = 'c';
             if (operand->type == MOJOSHADER_PRESHADEROPERAND_TEMP)
                 regch = 'r';
+            else if (operand->type == MOJOSHADER_PRESHADEROPERAND_INPUT)
+                regch = 'i';
+            else
+                regch = 'c';
 
             if (operand->array_register_count > 0)
             {
```

**Comment by kg** [comment]
yeah, the inregs = got lost when I rebased this, I just noticed it here. I think your diff is correct, but it's not clear to me whether this is the right solution - with this one of my shaders is less broken in /O3, but it's still broken.
I'd say maybe wait until I've had more time to verify what seems to be the right semantics here, since it's weird?

**Comment by flibitijibibo** [comment]
It may just write directly into the input registers instead of doing a copy, this extra logic only makes sense if they separate the preshader VM input from the constant buffer (which we're reading/writing directly to).

**Comment by kg** [comment]
```
        const size_t len = largest * sizeof (float) * 4;
        preshader->registers = (float *) Malloc(ctx, len);
```
i think my new registers array is too small...

**Comment by flibitijibibo** [comment]
Updated the diff accordingly.

**Comment by kg** [comment]
I dug out one of the preshaders so we can puzzle over what it's actually trying to do (I'll be looking at it later, just putting it here for future reference):
```

        PRESHADER:
            SYMBOLS:
                * 0: "DistanceField"
                  register set float4
                  register index 9
                  register count 5
                  symbol class struct
                  symbol type void
                  rows 1
                  columns 20
                  elements 1
                  MEMBERS:
                  MEMBERS:
                      * 0: "_ConeAndMisc"
                      symbol class vector
                      symbol type float
                      rows 1
                      columns 4
                      elements 1
                  MEMBERS:
                      * 1: "_TextureSliceAndTexelSize"
                      symbol class vector
                      symbol type float
                      rows 1
                      columns 4
                      elements 1
                  MEMBERS:
                      * 2: "_StepAndMisc2"
                      symbol class vector
                      symbol type float
                      rows 1
                      columns 4
                      elements 1
                  MEMBERS:
                      * 3: "TextureSliceCount"
                      symbol class vector
                      symbol type float
                      rows 1
                      columns 4
                      elements 1
                  MEMBERS:
                      * 4: "Extent"
                      symbol class vector
                      symbol type float
                      rows 1
                      columns 4
                      elements 1
                * 1: "Environment"
                  register set float4
                  register index 14
                  register count 1
                  symbol class struct
                  symbol type void
                  rows 1
                  columns 4
                  elements 1
                  MEMBERS:
                  MEMBERS:
                      * 0: "ZAndScale"
                      symbol class vector
                      symbol type float
                      rows 1
                      columns 4
                      elements 1
                * 2: "GBufferTexelSize"
                  register set float4
                  register index 15
                  register count 1
                  symbol class vector
                  symbol type float
                  rows 1
                  columns 2
                  elements 1
                * 3: "Viewport"
                  register set float4
                  register index 0
                  register count 9
                  symbol class struct
                  symbol type void
                  rows 1
                  columns 36
                  elements 1
                  MEMBERS:
                  MEMBERS:
                      * 0: "Projection"
                      symbol class column-major matrix
                      symbol type float
                      rows 4
                      columns 4
                      elements 1
                  MEMBERS:
                      * 1: "ModelView"
                      symbol class column-major matrix
                      symbol type float
                      rows 4
                      columns 4
                      elements 1
                  MEMBERS:
                      * 2: "ScaleAndPosition"
                      symbol class vector
                      symbol type float
                      rows 1
                      columns 4
                      elements 1

            mul r0.xy, c15.xy, c15.xy
            add r1.x, r0.y, r0.x
            neg r0.x, r1.x
            cmp c0.x, r0.x, (0), (1)
            neg r0.x, c12.x
            add r1.x, r0.x, (0.001)
            rcp r0.x, c12.x
            mul r1.y, r0.x, (0.333333)
            cmp c16.x, r1.x, (333.333), r1.y
            neg r0.x, c13.z
            add r1.x, r0.x, (0.001)
            rcp r0.x, c13.z
            cmp r2.x, r1.x, (1000), r0.x
            mul c15.x, r2.x, c12.w
            neg r0.x, c11.y
            add r1.x, r0.x, (1)
            cmp c14.x, r1.x, (1), c11.y
            rcp r0.x, c8.x
            rcp r0.y, c8.y
            mov c10.xy, r0.xy
            mov c13.xy, r0.xy
            rcp r0.x, c14.z
            mov c11.x, r0.x
            mov c12.x, r0.x
```

**Comment by flibitijibibo** [comment]
Looking closer it seems the temp inregs aren't needed since each preshader run gets a fresh copy and is not referenced later, so this is probably why skipping the assignment didn't change anything. Diff updated accordingly.

I also added a diff to make it more clear which input/output operands are being referenced. It seems pretty normal but maybe it's `cmp c0.x, r0.x, (0), (1)` that writes to input.

**Comment by kg** [comment]
Thanks, that was confusing. Deleted the old preshader text, here it is with your helpful diff
EDIT: argh, that clearly isn't the right one. I think it's this one:
```
        PRESHADER:
            SYMBOLS:
                * 0: "DistanceField"
                  register set float4
                  register index 9
                  register count 5
                  symbol class struct
                  symbol type void
                  rows 1
                  columns 20
                  elements 1
                  MEMBERS:
                  MEMBERS:
                      * 0: "_ConeAndMisc"
                      symbol class vector
                      symbol type float
                      rows 1
                      columns 4
                      elements 1
                  MEMBERS:
                      * 1: "_TextureSliceAndTexelSize"
                      symbol class vector
                      symbol type float
                      rows 1
                      columns 4
                      elements 1
                  MEMBERS:
                      * 2: "_StepAndMisc2"
                      symbol class vector
                      symbol type float
                      rows 1
                      columns 4
                      elements 1
                  MEMBERS:
                      * 3: "TextureSliceCount"
                      symbol class vector
                      symbol type float
                      rows 1
                      columns 4
                      elements 1
                  MEMBERS:
                      * 4: "Extent"
                      symbol class vector
                      symbol type float
                      rows 1
                      columns 4
                      elements 1
                * 1: "Environment"
                  register set float4
                  register index 14
                  register count 1
                  symbol class struct
                  symbol type void
                  rows 1
                  columns 4
                  elements 1
                  MEMBERS:
                  MEMBERS:
                      * 0: "ZAndScale"
                      symbol class vector
                      symbol type float
                      rows 1
                      columns 4
                      elements 1
                * 2: "GBufferTexelSize"
                  register set float4
                  register index 15
                  register count 1
                  symbol class vector
                  symbol type float
                  rows 1
                  columns 2
                  elements 1
                * 3: "Viewport"
                  register set float4
                  register index 0
                  register count 9
                  symbol class struct
                  symbol type void
                  rows 1
                  columns 36
                  elements 1
                  MEMBERS:
                  MEMBERS:
                      * 0: "Projection"
                      symbol class column-major matrix
                      symbol type float
                      rows 4
                      columns 4
                      elements 1
                  MEMBERS:
                      * 1: "ModelView"
                      symbol class column-major matrix
                      symbol type float
                      rows 4
                      columns 4
                      elements 1
                  MEMBERS:
                      * 2: "ScaleAndPosition"
                      symbol class vector
                      symbol type float
                      rows 1
                      columns 4
                      elements 1

            mul r0.xy, i15.xy, i15.xy
            add r1.x, r0.y, r0.x
            neg r0.x, r1.x
            cmp i0.x, r0.x, (0), (1)
            neg r0.x, i12.x
            add r1.x, r0.x, (0.001)
            rcp r0.x, i12.x
            mul r1.y, r0.x, (0.333333)
            cmp c16.x, r1.x, (333.333), r1.y
            neg r0.x, i13.z
            add r1.x, r0.x, (0.001)
            rcp r0.x, i13.z
            cmp r2.x, r1.x, (1000), r0.x
            mul c15.x, r2.x, i12.w
            neg r0.x, i11.y
            add r1.x, r0.x, (1)
            cmp c14.x, r1.x, (1), i11.y
            rcp r0.x, i8.x
            rcp r0.y, i8.y
            mov c10.xy, r0.xy
            mov c13.xy, r0.xy
            rcp r0.x, i14.z
            mov c11.x, r0.x
            mov c12.x, r0.x
```

**Comment by flibitijibibo** [comment]
>cmp i0.x, r0.x, (0), (1)

Called it!

So it writes to i0 and c10-c16, and reads from i8 and i11-15. A surprising amount of cruft comes from the fact that things are packed in structs but only a couple of the variables are used. The weird thing I'm seeing is that i0 is never referenced before or after, so it seems like it should be an output register. What does the shader's symbol table look like?

**Comment by flibitijibibo** [comment]
This has me wondering:

https://github.com/FNA-XNA/MojoShader/blob/fna/mojoshader.c#L2646

Can you check to see that nothing falls through all of the cases here? I'm now wondering if the dst operand is actually just zero'd memory and we're not parsing the last token for cmp operations, which are pretty different compared to everyone else.

**Comment by kg** [comment]
I'll check that out. Until now I had no idea I had any preshaders here, since fxc and AMD's analyzer both hide them... knowing what data it's using and how, I can pull stuff out of the structs so the preshaders can reach it. I went from a bunch of float uniforms to packed float4s, which probably made the preshaders more complex/wild in the process of making the real shaders denser and faster :/

**Comment by kg** [comment]
yep, fxlc.tokens[1] is 5 when parsing a preshader for the exact shader file that is broken.

**Comment by flibitijibibo** [comment]
Cool, so the actual issue is with the dst operand here. AFAIK input registers are never written to so thankfully everything we've written today can be thrown out. The real fix is to parse out the `5` token and this should be properly fixed after that.

**Comment by kg** [comment]
Thanks for helping me navigate this maze, these shaders are really sensitive to compilation differences and seemingly start or stop working at random :) Knowing now about this huge tangle of preshaders explains a lot. Glad to have testparse as a tool to analyze them now

**Comment by flibitijibibo** [comment]
Closing since we now know what the real issue is...

**Pull request closed without merging**
